drop table if exists public.codesAcces;
drop table if exists public.historiqueAcces;
drop table if exists public.historiqueContact;

create table public.codesAcces (
	detenteur VARCHAR(128) unique not null,
	code INTEGER unique not null
);

create table public.historiqueAcces (
	recordId INTEGER generated by default as identity primary key,
	ipAcces VARCHAR(32) not null,
	dateConnexion date default CURRENT_DATE,
	code INTEGER not null,
	dateFinAcces date default (CURRENT_DATE + interval '1 hour')
);

create table public.historiqueContact (
	idMessage			INTEGER generated by default as identity primary key,
	ipMessage			VARCHAR(32) not null,
	timestampMessage	BIGINT not null default 0,
	sujetMessage		VARCHAR(64) not null,
	corpsMessage		VARCHAR(1024) not null,
	telephone			VARCHAR(20) not null default '',
	email				VARCHAR(254) not null default ''
);
