drop table if exists public.codesAcces CASCADE;
drop table if exists public.historiqueAcces CASCADE;
drop table if exists public.messagesFormulaire CASCADE;
drop table if exists public.codesStatutSms CASCADE;
drop table if exists public.sms CASCADE;

create table public.codesAcces (
	detenteur VARCHAR(128) unique not null,
	code INTEGER PRIMARY KEY
);

create table public.historiqueAcces (
	recordId INTEGER generated by default as identity primary key,
	ipAcces VARCHAR(32) not null,
	dateConnexion date default CURRENT_DATE,
	code INTEGER not null,
	dateFinAcces date default (CURRENT_DATE + interval '1 hour'),

	CONSTRAINT fk_code_utilisateur FOREIGN KEY(code) REFERENCES public.codesAcces ON DELETE CASCADE
);

create table public.messagesFormulaire (
	idMessage			INTEGER generated by default as identity primary key,
	ipMessage			VARCHAR(32) not null,
	timestampMessage	BIGINT not null default 0,
	sujetMessage		VARCHAR(64) not null,
	corpsMessage		VARCHAR(1024) not null,
	telephone			VARCHAR(20) not null default '',
	email				VARCHAR(254) not null default ''
);

create table public.codesStatutSms (
	codeStatut	INTEGER PRIMARY KEY,
	codeDesc	VARCHAR(20) NOT NULL
);

create table public.sms (
	idSms		INTEGER generated by default as identity primary key,
	timeMsg		BIGINT not null default 0,
	content		VARCHAR(140) not null default '',
	codeStatut	INTEGER NOT NULL,

	CONSTRAINT fk_code_statut FOREIGN KEY (codeStatut) REFERENCES public.codesStatutSms ON DELETE CASCADE
);

INSERT INTO public.codesStatutSms (codeStatut, codeDesc) VALUES (200, 'Succès');
INSERT INTO public.codesStatutSms (codeStatut, codeDesc) VALUES (400, 'Paramètre manquant');
INSERT INTO public.codesStatutSms (codeStatut, codeDesc) VALUES (402, 'Rate limit');
INSERT INTO public.codesStatutSms (codeStatut, codeDesc) VALUES (403, 'Service désactivé');
INSERT INTO public.codesStatutSms (codeStatut, codeDesc) VALUES (500, 'Erreur serveur');
